version: "3.3"
services:
    reflected_cross_site_scripting:
        build: "./web"
        volumes:
            - "./web/app:/var/www/html"
        ports:
            - "80:80"
        networks:
            - dnet
            
    mysql:
        container_name: mysql_server
        image: mysql:5.6.40
        build: "./mysql"
        volumes:
            - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
        environment:
            - MYSQL_ROOT_PASSWORD=Password123!
        networks:
            - dnet
            
networks:
    dnet:
        driver: bridge